[package]
name = "pals"
version = "0.1.0"
authors = ["Jake Craige <jake@example.com>"]

[dependencies]
base64 = "0.9.3"
openssl = "0.10.12"
rand = "  0.5"
num-bigint = { version = "0.2", features = ["rand"] }
num-traits = "0.2"
num-iter = "0.1"
